# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512.xci
# IP: The module: 'fifo_128x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512/fifo_128x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128x512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512/fifo_128x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512.xci
# IP: The module: 'fifo_128x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512/fifo_128x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512/fifo_128x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/cho/hCODE_dev/hFPGA/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
