# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/hcode_shell.cache/wt [current_project]
set_property parent.project_path /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/hcode_shell.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files -quiet /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/pcie_k7_vivado/pcie_k7_vivado.dcp
set_property used_in_implementation false [get_files /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/pcie_k7_vivado/pcie_k7_vivado.dcp]
add_files -quiet /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512.dcp
set_property used_in_implementation false [get_files /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/fifo_128x512_1/fifo_128x512.dcp]
read_verilog -library xil_defaultlib {
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/hcode_shell_top.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/xillybus/pcie_k7_8x.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/xillybus/pcie_k7_8x_pipe_clock.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/xillybus/pcie_k7_vivado_pipe_clock.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/xillybus_interface.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/ip-src/ip_loopback.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/xillybus/xillybus.v
  /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/shell-src/xillybus/xillybus_core.v
}
set_property edif_extra_search_paths {$PPRDIR/core} [current_fileset]
read_edif /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/core/xillybus_core.ngc
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/constrain/hcode_shell.xdc
set_property used_in_implementation false [get_files /home/cho/hCODE_dev/hFPGA_z83/shell-vc707-xillybus-ap_fifo128-4ports/constrain/hcode_shell.xdc]


synth_design -top hcode_shell_top -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef hcode_shell_top.dcp

catch { report_utilization -file hcode_shell_top_utilization_synth.rpt -pb hcode_shell_top_utilization_synth.pb }
